name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 6 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - name: checkout
        uses: actions/checkout@v3.5.0

      - name: Download latest engine version
        uses: robinraju/release-downloader@v1.9
        with:
          repository: SakulFlee/Akimo-Project
          latest: true
          preRelease: false
          out-file-path: Akimo-Project.Engine-Web.zip
          fileName: Akimo-Project.Engine-Web.zip
          extract: true

      - name: Move extracted engine into static folder
        run: mv engine-web/ static/engine/

      - name: Remove downloaded ZIP
        run: rm Akimo-Project.Engine-Web.zip

      - name: Make path adjustments to engine
        run: sed -e s,/engine_web,/engine/engine_web,g -i static/engine/index.html

      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
